### ISSUE TITLE
[Bug] Replying to bot can trigger it again

### ISSUE THREAD

**Issue by davidmikan** [fmhall/Petrosian-Bot#4]
If one replies to the bots pasta, if the reply contains any keywords, it triggers again, and it even does so if the user replying to the bots comment is the one that triggered that comment in the first place. This happened for instance in this interaction:

- Me: [...] pipi [...]
- Bot: pasta
- Me: Thank you, Petrosian
- Bot: pasta

If you agree that this should be fixed, I would submit a pull request (3 lines of code) that prevents the bot from triggering if the original commenter replies to it's pasta.

**Comment by fmhall** [comment]
Resolved in #5
